global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['nas.lan:9100']
        labels: { alias: 'NAS' }
      - targets: ['media.lan:9100']
        labels: { alias: 'Media' }
      - targets: ['rede.lan:9100']
        labels: { alias: 'Rede' }

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['nas.lan:8081','media.lan:8081','rede.lan:8081']

