global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.0.121:9100']
        labels: { alias: 'NAS' }
      - targets: ['192.168.0.119:9100']
        labels: { alias: 'Media' }
      - targets: ['localhost:9100']        # a pr√≥pria VM Rede
        labels: { alias: 'Rede' }

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.0.121:8080','192.168.0.119:8081','192.168.0.122:8080']

