services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Fortaleza
    volumes:
      - ./config:/config
      - /mnt/media/downloads/movies:/media/movies
      - /mnt/media/downloads/series:/media/series
      - /mnt/media/downloads/music:/media/music
      - /mnt/media/downloads/animes:/media/animes
      - /opt/containers/jellyfin/cache:/cache
    ports:
      - "8096:8096"
    restart: unless-stopped

