services:
  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "9001:9001"  # Porta por onde o Server se conecta no Agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    # security_opt:
    #   - no-new-privileges:true
    # cap_drop:
    #   - ALL
