services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000     # ajuste com seu UID real
      - PGID=1000     # ajuste com seu GID real
      - TZ=America/Fortaleza
      - WEBUI_PORT=8080
    volumes:
      - ./config:/config
      - /mnt/media/downloads:/downloads
    ports:
      - "8080:8080"      # WebUI
      - "6881:6881"      # BitTorrent TCP
      - "6881:6881/udp"  # BitTorrent UDP
    restart: unless-stopped
