- name: kiosk
  hide-desktop-navigation: true

  columns:
    - size: small
      widgets:
        - type: clock
          hour-format: 24h
          timezones:
            - timezone: America/Fortaleza
              label: Cluster
            - timezone: America/Vancouver
              label: Vancouver

        - type: calendar
          first-day-of-week: monday

        - type: rss
          title: Notícias
          limit: 5
          collapse-after: 3
          cache: 12h
          feeds:
            - url: https://g1.globo.com/rss/g1/politica
              title: Política
            - url: https://rss.nytimes.com/services/xml/rss/nyt/World.xml
              title: World

    - size: full
      widgets:
        - type: monitor
          title: Node Status
          sites:
            - title: Portainer
              url: http://rede.lan:9000
              icon: si:portainer # Use um ícone relevante, como o Python (Glances é Python)
              hide-arrow: true # Esconde a seta para um visual mais limpo
              same-tab: true # Abre na mesma aba (útil se você quer ir para a página)        
